### PR TITLE
added support for exporting to csv

### LINKED ISSUE #1: Add export to CSV capability
- should default to using column definitions
- should have optional ability to provide custom definitions
- needs to be flexible enough to provide a one-to-many row export (for rows with child data)

### PR DESCRIPTION
**Pull request by jpollard-cs**
basically added a convenience function that can be hooked up to any button
resolves [https://github.com/jpollard-cs/flexable/issues/1](https://github.com/jpollard-cs/flexable/issues/1)

### CODE REVIEW

**Comment by jpollard-cs** [comment]
@amcintyre-cs please let me know if you're able to comment on this or not

**Comment by raglan-road** [comment]
Everyone's dumping reviews on my today. Who am I, @dkotin-cs?

**Comment by dkotin-cs** [comment]
Oh, I have one coming your way too :D

**Comment by raglan-road** [comment]
Fine, we can trade this for that.

**Comment by dkotin-cs** [comment]
Only bad things will happen if you send this my way

**Comment by raglan-road** [comment]
I'm not afraid of you!

**Comment by dkotin-cs** [comment]
Miaouuuuuu

**Comment by jpollard-cs** [comment]
@dkotin-cs you embed images like so: `Alt Text`
I've fixed it for you this time, but don't let it happen again! :disappointed: 
Also FYI this is all public so now everyone knows you don't know how to use Markdown!

**Pull request merged**
